apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-ehgaurzh
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-ehgaurzh:e3ed626bc9c1bb479e7e399054961a2fc4b93165@sha256:679b532735de2cf7ea20fa3e6500b0dcc5eaed60521aeee71d72faac87c9727b
        name: container-image  
